-- Agritek database schema + seed data
-- Import this in phpMyAdmin into a database named `agritek`.

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(120) NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('buyer','farmer','admin') NOT NULL DEFAULT 'buyer',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_username (username),
  UNIQUE KEY uniq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  price_php DECIMAL(10,2) NOT NULL,
  unit VARCHAR(20) NOT NULL DEFAULT 'kg',
  harvest_date DATE NULL,
  image_url TEXT NULL,
  description TEXT NULL,
  farmer_name VARCHAR(120) NULL,
  farmer_location VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Users are seeded by running seed.php (so password hashes are generated by PHP).

-- Seed products
INSERT INTO products (name, price_php, unit, harvest_date, image_url, description, farmer_name, farmer_location)
VALUES
  ('Tomatoes', 50.00, 'kg', '2026-03-15', 'https://upload.wikimedia.org/wikipedia/commons/8/89/Tomato_je.jpg', 'Fresh farm product', 'John Doe', 'Farmville'),
  ('Carrots', 40.00, 'kg', '2026-03-10', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTahFx9p794CNcW772o5HzLdlseehKkil0jJQ&s', 'Fresh farm product', 'John Doe', 'Farmville'),
  ('Cabbage', 35.00, 'kg', '2026-03-12', 'https://hasora.in/cdn/shop/products/SquareSimple_2_6bc8140f-7fb9-42d1-81b7-183f85f2ae04.jpg?v=1613637220', 'Fresh farm product', 'John Doe', 'Farmville'),
  ('Eggplant', 45.00, 'kg', '2026-03-18', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYvZ6bvm3FQEfZtqQTdDe2TXYmI_iKiJiX6g1kDz8cpHiToaX4bOidcb1UHKpqiimDt46Bz3PfdpxhiWob9EmR9kzeiaIN4a5aMwhHxQ&s=10', 'Fresh farm product', 'John Doe', 'Farmville')
;
